### ISSUE TITLE
Re-enable queue creation in Azure

### ISSUE THREAD

**Issue by TiS** [assoconnect/enqueue-azure#14]
Queue creation has been disabled in Azure Storage Context, due to exceptions being sometimes thrown when queues already exist.

This should be re-enabled.

PR in progress.

**Comment by TiS** [comment]
@sylfabre @jwaguet - PR created for this issue. Please, review.

As you have encountered queue creation exceptions, you may want to test, if this PR resolves them (while still giving possibility to create queues in Azure).

**Comment by sylfabre** [comment]
Fixed by https://github.com/assoconnect/enqueue-azure/pull/15
